### ISSUE TITLE
Unable to download SPK package from imnks source

### ISSUE THREAD

**Issue by szyb** [szyb/synopackage_dotnet#276]

**Comment by szyb** [comment]
error from logs:
```System.Net.WebException The remote server returned an error: (301) Moved Permanently.    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at synopackage_dotnet.Model.Services.DownloadSpkService.IsRemoteFileAvailable(String link) in [cut]\synopackage_dotnet\synopackage_dotnet.model\Model\Services\DownloadSpkService.cs:line 144 System.Net.WebResponse EndGetResponse(System.IAsyncResult)```

**Comment by szyb** [comment]
There are 2 redirections made:
1) from http to https
2) then to http://dl.imnks.com:8888

need to investigate why this is an issue

**Comment by szyb** [comment]
Debugging. When I tried to download  SPK file from imnks server I got the following image (instead od SPK file). 
Anyone knows what it is? I guess that this is kind of hotlinking protection, isn't?
![cpolar_x64-6 1_3 2 86 16-1](https://user-images.githubusercontent.com/1598139/158463835-f21256c7-5317-47ce-8090-5ed6777f293a.png)

**Comment by szyb** [comment]
Now this website does not allow to download packages manually from web browser (only from Package Center). This is the only SPK source that works in that way. Need to: 
1) Give a information about problems with downloading pacakges, or/and:
2) Remove download SPK button for both imnks servers.

It's not a bug then... remove the bug label
